chore: updates

diff --git a/zsh/zshfuncs b/zsh/zshfuncs
--- a/zsh/zshfuncs
+++ b/zsh/zshfuncs
@@ -355,3 +355,25 @@ gbpn()
   echo ""
   echo "Done"
 }
+
+### Project Planning
+proj()
+{
+  command -v minijira >/dev/null 2>&1 || { echo "🚨 minijira not found"; exit 1; }
+
+  if [ $# -eq 0 ]; then
+    minijira
+  else
+    minijira "$1"
+  fi
+}
+
+pb()
+{
+  proj brain
+}
+
+prl()
+{
+  proj replog
+}
